version: '3.8'

services:
  nuxt-app:
    image: "nuxt-app:1.0"
    container_name: "test"
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped